// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ6t-KTCTkrddtnxYt_0tOeeHl05G6Dd0',
    appId: '1:909279787138:android:8a19ae52b34d92b908dc9b',
    messagingSenderId: '909279787138',
    projectId: 'notify-test-fd4ee',
    storageBucket: 'notify-test-fd4ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGMOpcxarTnTWTh083Yypbpu7e3YANzVE',
    appId: '1:909279787138:ios:28048a075311243d08dc9b',
    messagingSenderId: '909279787138',
    projectId: 'notify-test-fd4ee',
    storageBucket: 'notify-test-fd4ee.appspot.com',
    iosBundleId: 'com.hussein.tv.husseintvtheori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD12gHbHgyl_WcDGF1GyunNTBxsJgzxMco',
    appId: '1:909279787138:web:918a608919aca07608dc9b',
    messagingSenderId: '909279787138',
    projectId: 'notify-test-fd4ee',
    authDomain: 'notify-test-fd4ee.firebaseapp.com',
    storageBucket: 'notify-test-fd4ee.appspot.com',
    measurementId: 'G-K56BZZRCTH',
  );
}
